import { useState, useMemo } from 'react';
import { gamificationApi } from '../../api/gamification';
import styles from './Training.module.css';

interface QuizQuestion {
  questionText: string;
  options: { letter: string; text: string }[];
  correctLetter: string;
}

/** Parse HTML test content generated by seed's format_test() into structured quiz questions */
function parseQuizHTML(html: string): QuizQuestion[] {
  const questions: QuizQuestion[] = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const cards = doc.querySelectorAll('div[style*="margin-bottom"]');

  cards.forEach(card => {
    const qEl = card.querySelector('p[style*="font-weight"]');
    if (!qEl) return;
    const questionText = qEl.textContent?.replace(/^Вопрос\s*\d*\.\s*/, '').trim() || '';

    const options: { letter: string; text: string }[] = [];
    const optContainer = card.querySelector('div[style*="flex-direction"]');
    if (optContainer) {
      optContainer.querySelectorAll('div[style*="border-radius"]').forEach(optDiv => {
        const txt = optDiv.textContent?.trim() || '';
        const m = txt.match(/^([а-гa-d])\)\s*(.*)/i);
        if (m) options.push({ letter: m[1].toLowerCase(), text: m[2] });
      });
    }

    let correctLetter = '';
    const correctEl = card.querySelector('p[style*="color:#16a34a"], p[style*="color: #16a34a"]');
    if (correctEl) {
      const ct = correctEl.textContent?.trim() || '';
      const cm = ct.match(/Correct:\s*([а-гa-d])/i);
      if (cm) correctLetter = cm[1].toLowerCase();
    }

    if (options.length > 0) {
      questions.push({ questionText, options, correctLetter });
    }
  });

  return questions;
}

interface QuizRendererProps {
  html: string;
  topicId?: string;
  onTestPassed?: () => void;
}

export default function QuizRenderer({ html, topicId, onTestPassed }: QuizRendererProps) {
  const questions = useMemo(() => parseQuizHTML(html), [html]);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);

  if (questions.length === 0) {
    return <div className={styles.emptyContent}>Тест не содержит вопросов</div>;
  }

  const handleSelect = (qIdx: number, letter: string) => {
    if (submitted) return;
    setAnswers(prev => ({ ...prev, [qIdx]: letter }));
  };

  const handleSubmit = async () => {
    setSubmitted(true);
    const score = questions.reduce((acc, q, i) => acc + (answers[i] === q.correctLetter ? 1 : 0), 0);
    if (topicId) {
      setSaving(true);
      try {
        const { data } = await gamificationApi.submitTest({ topic_id: topicId, score, total: questions.length });
        if (data.passed && onTestPassed) onTestPassed();
      } catch { /* ignore */ }
      finally { setSaving(false); }
    }
  };

  const handleReset = () => {
    setAnswers({});
    setSubmitted(false);
  };

  const correctCount = questions.reduce((acc, q, i) => acc + (answers[i] === q.correctLetter ? 1 : 0), 0);
  const answeredAll = Object.keys(answers).length === questions.length;

  return (
    <div>
      {questions.map((q, qIdx) => {
        const selected = answers[qIdx];
        return (
          <div key={qIdx} className={styles.questionCard}>
            <div className={styles.questionText}>
              {qIdx + 1}. {q.questionText}
            </div>
            <div className={styles.questionOpts}>
              {q.options.map(opt => {
                let cls = styles.quizOpt;
                if (selected === opt.letter) cls += ' ' + styles.quizSel;
                if (submitted) {
                  if (opt.letter === q.correctLetter) cls = styles.quizOpt + ' ' + styles.quizRight;
                  else if (selected === opt.letter && opt.letter !== q.correctLetter) cls = styles.quizOpt + ' ' + styles.quizWrong;
                }
                return (
                  <label key={opt.letter} className={cls} onClick={() => handleSelect(qIdx, opt.letter)}>
                    <input type="radio" name={`q${qIdx}`} checked={selected === opt.letter} readOnly />
                    <span>{opt.letter}) {opt.text}</span>
                  </label>
                );
              })}
            </div>
          </div>
        );
      })}

      <div style={{ display: 'flex', gap: 10, marginTop: 16, alignItems: 'center', flexWrap: 'wrap' }}>
        {!submitted ? (
          <button className={styles.btnPrimary} onClick={handleSubmit} disabled={!answeredAll || saving}>
            {saving ? 'Сохраняем...' : 'Проверить ответы'}
          </button>
        ) : (
          <button className={styles.btnGray} onClick={handleReset} disabled={saving}>
            Пройти заново
          </button>
        )}
        {submitted && (
          <div className={styles.testResult}>
            Результат: <strong style={{ marginLeft: 4 }}>{correctCount}</strong> из <strong>{questions.length}</strong>
            {correctCount === questions.length
              ? <span style={{ color: '#16a34a', fontWeight: 700, marginLeft: 8 }}>Отлично!</span>
              : correctCount >= questions.length * 0.7
                ? <span style={{ color: '#ca8a04', fontWeight: 700, marginLeft: 8 }}>Хорошо</span>
                : <span style={{ color: '#dc2626', fontWeight: 700, marginLeft: 8 }}>Попробуйте ещё</span>}
          </div>
        )}
      </div>
    </div>
  );
}
